kind: SubPipeline
apiVersion: tekton.ba.dev/v1beta1
metadata:
  name: hello-sub-pipeline
spec:
  pipelineSpec:
    tasks:
      - name: hello-from-subpipeline
        taskSpec:
          steps:
            - name: echo
              image: alpine
              script: |
                #!/usr/bin/env sh
                echo "Hello World!"
      - name: bye-from-subpipeline
        taskSpec:
          steps:
            - name: echo
              image: alpine
              script: |
                #!/usr/bin/env sh
                echo "Bye World!"